# custom-values.yaml
# ─────────────────────────────────────────────────────────────
# Yeh file sirf CI/CD ke liye hai
# Original values.yaml ko touch mat karo
# CI automatically "version" field update karta hai
# ─────────────────────────────────────────────────────────────

image:
  repo: chauhanshreyash18
  version: 8ecc43fb7c47ee9a88672fed13d802a2b563e2eb
  pullPolicy: Always     # ← naya image hamesha pull hoga

# Baaki sab original values.yaml se aayega
# Yahan kuch aur likhne ki zaroorat nahi
