# custom-values.yaml
# ─────────────────────────────────────────────────────────────
# Yeh file sirf CI/CD ke liye hai
# Original values.yaml ko touch mat karo
# CI automatically "version" field update karta hai
# ─────────────────────────────────────────────────────────────

image:
  repo: chauhanshreyash18
  version: 458b899847701c87a1315a4ed43d9c568299a3a8
  pullPolicy: Always     # ← naya image hamesha pull hoga

# Baaki sab original values.yaml se aayega
# Yahan kuch aur likhne ki zaroorat nahi
